sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
env:
  global:
  - secure: BxqIu8Wnq4+u8TusFUeCN5IBwrePoM+sRnnE5UGyWlpGnrCZW9xhXPeRVoPRQCZu7Ya6hj69YthW8W3arQuogukjRy9f8Rverf1IW3CTYlK2ZWpsKdPlYJMR9NWAzTE+OaC+yDuMaa+83dLF/OCiY1qWtvsBvSQEypnCdNxuPNs=
  - GIT_CONFIG_PARAMETERS="'remote.github.url=https://${TOKEN}@github.com/kontron/robotframework-snmplibrary.git'"
install: pip install -e .
script: nosetests
after_script:
- PYTHONPATH=src python -m robot.libdoc SnmpLibrary /tmp/SnmpLibrary.html
- git remote set-branches --add origin gh-pages
- git fetch origin
- git checkout gh-pages
- mv /tmp/SnmpLibrary.html .
- git add SnmpLibrary.html
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git commit -m "autogen libdoc ($(date -R))"
- git push github gh-pages 2>&1 | grep -v http
deploy:
  provider: pypi
  user: mwalle
  password:
    secure: oyiryGHQlfYeGY0g5OQgh6gHAhmYsxpg8qg4l7C/m0HSGLxg0OQ+tt/UBPFlq2Kp/IVfg5RtwrS1Q8wekoVqsSlFqotSohBMTacXgGURp6u2PYGpp8z994FLzqX+Ub7IqrxyIRDx1gI9fyb4j83S+Z7Bd3gamuj3qv9SfwSoLug=
  on:
    tags: true
    distributions: "release"
